### ISSUE TITLE
NOX index stuck on 1

### ISSUE THREAD

**Issue by remyhx** [Sensirion/gas-index-algorithm#1]
Hi,

I can communicate with the SGP41, get raw results (also with valid CRC) VOC like 27000-30000 raw and NOX 16000-17000 raw).

When I process them with GasIndexAlgorithm_process() I get nice VOC indexes which also alter with ventilation. I live next to a busy point in a middle sized city and the NOX index starts at 0, but always stays at 1. With a 24hr check, it is never changed.

How can we verify the algoritm?  (like with VOC i sometimes spray some ethanol in the room to check the VOC)

I made two structs:

GasIndexAlgorithmParams VocPar;
GasIndexAlgorithmParams NoxPar;

They are initialised with:

 GasIndexAlgorithm_init(&VocPar, GasIndexAlgorithm_ALGORITHM_TYPE_VOC);
 GasIndexAlgorithm_init(&NoxPar, GasIndexAlgorithm_ALGORITHM_TYPE_NOX);

And processed:

GasIndexAlgorithm_process(&VocPar, (int)rawticks, &VOCI);
and
GasIndexAlgorithm_process(&NoxPar, (int)rawticks, &NOXI); (in another function)

The raw value of NOX changes, isn't fixed at one specific number.

LIBRARY_VERSION_NAME "3.1.0"

**Comment by psachs** [comment]
The NOx and VOC algorithms both require some stable environment for initialization. An NOx value of 1 is the default average index.
There are parameters to configure the behavior. So if you don't have enough NOx in your environment to trigger an event recognized by the algorithm, it's best to play with the parameters.

Please check out the technical description for the SVM41 eval kit to get more information about the parameters, or check the interface description of the `set_tuning_parameters` interface.
* https://github.com/Sensirion/gas-index-algorithm/blob/cae2ae2139d0e4b1877040b748c5c3dec50f5356/sensirion_gas_index_algorithm/sensirion_gas_index_algorithm.h#L251
* https://sensirion.com/media/documents/FBD0A26B/61EA8BFA/Sensirion_Gas_Sensors_SEK-SVM4x_Technical_Description.pdf

**Comment by remyhx** [comment]
Ok i will do, although it feels like the value of measuring is too much changeable between devices.

Looking at the parameters, guess only index offset and gain factor are most interesting. Running now a test with first a higher gain. 

Wonder why it is that NOx starts at 1 and VOC at 100.

Gr and thx for the reply, Remy

NB: highest now was 2 instead of 1, since i wrote the message ;)


* Set parameters to customize the gas index algorithm. Call this once after
 * GasIndexAlgorithm_init() and before optional GasIndexAlgorithm_set_states(),
 * if desired. Otherwise, the default values will be used.
 *
 * @param params                      Pointer to the GasIndexAlgorithmParams
 *                                    struct
 * @param index_offset                Gas index representing typical (average)
 *                                    conditions. Range 1..250,
 *                                    default 100 for VOC and 1 for NOx
 * @param learning_time_offset_hours  Time constant of long-term estimator for
 *                                    offset. Past events will be forgotten
 *                                    after about twice the learning time.
 *                                    Range 1..1000 [hours], default 12 [hours]
 * @param learning_time_gain_hours    Time constant of long-term estimator for
 *                                    gain. Past events will be forgotten
 *                                    after about twice the learning time.
 *                                    Range 1..1000 [hours], default 12 [hours]
 *                                    NOTE: This value is not relevant for NOx
 *                                    algorithm type
 * @param gating_max_duration_minutes Maximum duration of gating (freeze of
 *                                    estimator during high gas index signal).
 *                                    0 (no gating) or range 1..3000 [minutes],
 *                                    default 180 [minutes] for VOC and
 *                                    720 [minutes] for NOx
 * @param std_initial                 Initial estimate for standard deviation.
 *                                    Lower value boosts events during initial
 *                                    learning period, but may result in larger
 *                                    device-to-device variations.
 *                                    Range 10..5000, default 50
 *                                    NOTE: This value is not relevant for NOx
 *                                    algorithm type
 * @param gain_factor                 Factor used to scale applied gain value
 *                                    when calculating gas index. Range 1..1000,
 *                                    default 230
 */

**Comment by psachs** [comment]
Hi,

You can increase the gain factor to detect smaller events easier.

The index for VOC is at 100 because there are VOCs present in most indoor environment. NOx are usually no present or only in really small amount and have negative health impact if exposed to it over longer periods. Therefore small index of 1 is more accurate to describe it.
It is also expected that you don't have a high NOx index at most places and only see events that create NOx
