### ISSUE TITLE
How to install package on Ubuntu Linux system

### ISSUE THREAD

**Issue by ds-digid** [Sensirion/gas-index-algorithm#12]
Hi, I have tried to evaluate the SGP41 on a desktop PC with ubuntu 22.04.4 

I have installed a virtual environment and tried: 

pip install sensiron-gas-algorithm

The Error I got then was:
ERROR: Could not find a version that satisfies the requirement sensiron-gas-algorithm (from versions: none)
ERROR: No matching distribution found for sensiron-gas-algorithm

Is there a way to solve this error?

kind regards
David

**Comment by sdmueller** [comment]
Hi @ds-digid 

The package is called `sensirion-gas-index-algorithm` not `sensirion-gas-algorithm`.

Installing it as follows should work:
`pip install sensirion-gas-index-algorithm`

**Comment by ds-digid** [comment]
Thank you for clarification
