### ISSUE TITLE
SGP41 VOC NOx index algorithm in low power mode

### ISSUE THREAD

**Issue by jeromecandau** [Sensirion/gas-index-algorithm#14]
I have been using SGP41 sensors in combination with SHT41 for two or three years now. It works really well with a raspberry pi zero 2 with the algorithm provided by Sensirion. However, the self-heating is quite significant and I would like to use them in a "low power" mode. Such an algorithm seems to be provided for the SGP40 (VOC) but I can't find one for the SGP41 (VOC and NOx). Is there one and, if so, where can I find it? Thanks, Jerome CANDAU

**Comment by qfisch** [comment]
Hello Jerome,
Unfortunately the NOx measurement requires a conditioning period (10 seconds recommended), during which the sensor's hotplate come to a stable temperature hence allowing faster measurements.
As you might guess, it makes a low power mode irrelevant (sampling rate 1s or 10s).

Cheers
Q
