### ISSUE TITLE
Humidity Compensation Ticks

### ISSUE THREAD

**Issue by K0I05** [Sensirion/gas-index-algorithm#16]
The humidity compensation conversion to ticks gave erroneous results.

Suggest changing this formula:
`*compensation_rh = (uint16_t)s_rh * 65535 / 100;`

To the following:
`*compensation_rh = (uint16_t)llround(humidity * 65535 / 100);`

**Comment by LeonieFierz** [comment]
Thank you @K0I05 for reporting this bug. We fixed it on the master.
