### ISSUE TITLE
VOC index gets stuck at 400+ value

### ISSUE THREAD

**Issue by kimsniper** [Sensirion/gas-index-algorithm#2]
Hi,

We have this device that does air quality monitoring utilizing several sensors from Sensirion including the SGP40. Everything seems to be working fine when booted but VOC index value gets stuck at a certain value (400+) after some time. The value goes up 400+ when tested with Alcohol so the SGP40 is working, but it never goes down below 400 approx. SGP40 works fine if the device is rebooted. We are testing 4 devices and all of them shows the same result. Our device includes the following sensors:

    * CO2 - SCD4X
    * Temp/Hum  - SHT
    * TOF - Other vendor
    * Particulate Matter - SPS30

Further details:
    * The device runs on a 32 bit microcontroller
    * Same problems occurs when using the previous VOC index algorithm and the new GAS index Algorithm
    * The device has a very small and compact form factor with proper ventilation through holes all over its body
    * Sample code provided was used, no modification of the Gas index algorithm source code was done. 
    * No humidity compensation (Default compensation was used) so I skipped step 2 of this sample code https://github.com/Sensirion/gas-index-algorithm/blob/master/examples/raspberry-pi/low_power_example.c
    * All other sensors are working fine
    * Communication: I2C

Questions:
    * What might be causing this problem? (sgp40's internal temperature might be rising inside the enclosure? etc.)
    * Is it an issue on our hardware?

**Comment by psachs** [comment]
Hi @kimsniper 

Does you VOC index also rise to 400+ without you creating an event using alcohol?
Independent if there is an event or not, the index should go down after 3h of operation. If the index stays on 400+ for longer, we suspect an error in the implementation for your microcontroller.
Are you using a SHT40 humidity sensor and do you use this sensor for compensation?

The SGP40 is a MOX based sensor and therefore depending on the environment and previous handling needs operation time until it functions accurate. It would be best to initially let them run for 12h or more and also ensure that there is a "fresh air" event.

To help debugging if there is an issue with the implementation, we would need the raw voc ticks alongside the voc index values. If it is possible to recorde those values for at least a couple of minutes we can have a look at the data.

**Comment by kimsniper** [comment]
Hi @psachs 

Thank you for your response, kindly see below.

Does you VOC index also rise to 400+ without you creating an event using alcohol?
- We did some tests using the substance and had positive results. As for the specific event that's causing the index to get steady at 400+ value we aren't sure since my co workers in the office are using alcohol as well. We can only notice the reading gets stuck after we check the device for some time.

Independent if there is an event or not, the index should go down after 3h of operation.
- We did confirm this yesterday, the VOC index value got stuck for a few hours and then back to normal. Can we say that the values we are having are valid?

Are you using a SHT40 humidity sensor and do you use this sensor for compensation?
- Yes we are using it, but we are not using the humidity compensation for the sgp40 to work independently should the SHT malfunctions(internal hardware issues such as enclosure heating). Is it better to have compensation?

It would be best to initially let them run for 12h or more
- We will test this also since we turn our devices on/off everyday (Testing stage)
