### ISSUE TITLE
Running algorithm on micropython

### ISSUE THREAD

**Issue by SamarShahin** [Sensirion/gas-index-algorithm#5]
Got a hat with the Sensirion SPG40 for raspberry pi pico.
How do I get this running on micropython?

**Comment by psachs** [comment]
I will close this thread as it duplicates the following issue: https://github.com/Sensirion/gas-index-algorithm/issues/4
Lets discuss all questions related to micropython there.

If you want to use the c-code you can simply include the c and header file into you project and use it as defined in the interface description.
