### ISSUE TITLE
how to convert voc index to ppm

### ISSUE THREAD

**Issue by 1TTT9** [Sensirion/gas-index-algorithm#7]
Hi sirs,  thanks for this great chip as well as the libraries your company provided. I did tried chip SGP40, acquired VOC index through your company's gas-index-algorithm and it works just fine. However, as we would like to the air quality in PPM unit and have no idea to convert with each other. could you please help for that. Thanks in advanced.

**Comment by LeonieFierz** [comment]
Hi, 
SGP40 does actually not provide a value in PPM neither there is a formula to convert the measured value to it. The raw value you get is in so called VOC ticks (these ticks are proportional to the logarithm of the resistance of the sensing material), which are then usually process by the VOC algorithm to get a VOC index. You can set the algorithm parameters to fit your use case.

**Comment by 1TTT9** [comment]
Thanks for detailed explanation. I thought you might have an equation to convert voc index into ppm as your SPEC mentioned the measurement range (ppm unit) of TVOC. I will read the source codes and figure it out myself. Thanks again for your kind suggestion.

**Comment by flisboac** [comment]
@1TTT9 I know this is a very delayed answer, and I'm possibly necroposting here, but in 2023-04 an application note was released regarding standards compliance, and in that documentation it is explained a possible way to convert VOC index to TVOC PPM. Please take a look: https://sensirion.com/media/documents/4B4D0E67/6520038C/GAS_AN_SGP4x_BuildingStandards_D1_1.pdf

Apparently, the conversion algorithm only works for VOC. I wish the same could be applied to NOX index as well.
